<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.huaweicloud.sdk</groupId>
        <version>3.1.217</version>
        <artifactId>huaweicloud-sdk</artifactId>
    </parent>
    <groupId>com.huaweicloud.sdk</groupId>
    <artifactId>huaweicloud-sdk-services</artifactId>
    <version>3.1.217</version>
    <packaging>pom</packaging>
    <name>Huawei Cloud SDK for Java Services</name>
    <description>Services code for Huawei Cloud SDK for Java</description>
    <url>https://github.com/huaweicloud/huaweicloud-sdk-java-v3</url>

    <modules>
        <module>dsc</module>
        <module>er</module>
        <module>cloudtest</module>
        <module>coc</module>
        <module>organizations</module>
        <module>dds</module>
        <module>as</module>
        <module>idmeclassicapi</module>
        <module>codeartsrepo</module>
        <module>csms</module>
        <module>rfs</module>
        <module>dss</module>
        <module>evs</module>
        <module>cae</module>
        <module>metastudio</module>
        <module>rc</module>
        <module>bcc</module>
        <module>frs</module>
        <module>ddm</module>
        <module>cc</module>
        <module>kafka</module>
        <module>dcos</module>
        <module>cloudide</module>
        <module>nlp</module>
        <module>cce</module>
        <module>apig</module>
        <module>drs</module>
        <module>ga</module>
        <module>tics</module>
        <module>iam</module>
        <module>codeartspipeline</module>
        <module>geip</module>
        <module>vcm</module>
        <module>hss</module>
        <module>ims</module>
        <module>vpc</module>
        <module>dns</module>
        <module>gaussdbfornosql</module>
        <module>functiongraph</module>
        <module>bms</module>
        <module>mpc</module>
        <module>devstar</module>
        <module>eg</module>
        <module>codeartside</module>
        <module>codeartsbuild</module>
        <module>cbh</module>
        <module>dris</module>
        <module>clouddc</module>
        <module>antiddos</module>
        <module>agentarts</module>
        <module>projectman</module>
        <module>lts</module>
        <module>osm</module>
        <module>dwr</module>
        <module>cse</module>
        <module>pangulargemodels</module>
        <module>mapds</module>
        <module>versatile</module>
        <module>cloudtable</module>
        <module>identitycenterscim</module>
        <module>dc</module>
        <module>ces</module>
        <module>cdm</module>
        <module>mas</module>
        <module>ief</module>
        <module>waf</module>
        <module>mrs</module>
        <module>meeting</module>
        <module>moderation</module>
        <module>agentidentity</module>
        <module>eds</module>
        <module>eps</module>
        <module>ucs</module>
        <module>gsl</module>
        <module>iotdm</module>
        <module>ivs</module>
        <module>voicecall</module>
        <module>idme</module>
        <module>rds</module>
        <module>image</module>
        <module>esw</module>
        <module>bssintl</module>
        <module>workspaceapp</module>
        <module>oa</module>
        <module>ram</module>
        <module>sis</module>
        <module>dataartsfabricep</module>
        <module>aad</module>
        <module>smn</module>
        <module>aom</module>
        <module>vpn</module>
        <module>aos</module>
        <module>bss</module>
        <module>lakeformation</module>
        <module>edgesec</module>
        <module>astrozero</module>
        <module>identitycenter</module>
        <module>workspace</module>
        <module>cpcs</module>
        <module>live</module>
        <module>gaussdb</module>
        <module>classroom</module>
        <module>codecraft</module>
        <module>oroas</module>
        <module>rabbitmq</module>
        <module>msgsms</module>
        <module>rgc</module>
        <module>modelarts</module>
        <module>iotedge</module>
        <module>vias</module>
        <module>ocr</module>
        <module>eip</module>
        <module>sa</module>
        <module>dgc</module>
        <module>hilens</module>
        <module>kvs</module>
        <module>iamaccessanalyzer</module>
        <module>koophone</module>
        <module>swr</module>
        <module>sdrs</module>
        <module>koomap</module>
        <module>identitycenterportalapi</module>
        <module>dcs</module>
        <module>cpts</module>
        <module>ccm</module>
        <module>res</module>
        <module>ges</module>
        <module>mastudio</module>
        <module>rms</module>
        <module>ugo</module>
        <module>dataartsfabric</module>
        <module>css</module>
        <module>codeartsdeploy</module>
        <module>imagesearch</module>
        <module>dcc</module>
        <module>cdn</module>
        <module>dataartsstudio</module>
        <module>elb</module>
        <module>cph</module>
        <module>scm</module>
        <module>apm</module>
        <module>bcs</module>
        <module>gaussdbforopengauss</module>
        <module>vas</module>
        <module>expert</module>
        <module>deh</module>
        <module>obs</module>
        <module>cts</module>
        <module>cbs</module>
        <module>nat</module>
        <module>smnglobal</module>
        <module>identitycenterstore</module>
        <module>vpcep</module>
        <module>iotanalytics</module>
        <module>codeartsinspector</module>
        <module>sts</module>
        <module>optverse</module>
        <module>kms</module>
        <module>dataartsinsight</module>
        <module>campusgo</module>
        <module>koomessage</module>
        <module>ecs</module>
        <module>ec</module>
        <module>iotda</module>
        <module>kps</module>
        <module>cloudrtc</module>
        <module>cloudpond</module>
        <module>dli</module>
        <module>codeartscheck</module>
        <module>codeartsgovernance</module>
        <module>dis</module>
        <module>dlf</module>
        <module>orgid</module>
        <module>smsapi</module>
        <module>dws</module>
        <module>dbss</module>
        <module>mssi</module>
        <module>aidatalake</module>
        <module>servicestage</module>
        <module>sfsturbo</module>
        <module>iec</module>
        <module>cms</module>
        <module>das</module>
        <module>secmaster</module>
        <module>rocketmq</module>
        <module>tms</module>
        <module>codeartsartifact</module>
        <module>roma</module>
        <module>asm</module>
        <module>sms</module>
        <module>config</module>
        <module>vod</module>
        <module>eihealth</module>
        <module>identitycenteroidc</module>
        <module>oms</module>
        <module>cbr</module>
        <module>cfw</module>
    </modules>
</project>
